dz5
TTurkevich/game pull request #2
Opened 2022-06-22 14:14 UTC by TTurkevich

Сверстать экраны финального результата игры (4 и 5) и реализовать вывод результата игры. 

На финальном экране должно присутствовать: 

- Время, затраченное на партию.
- Статус игры в виде текста и иконки (выиграл/ проиграл).
- Кнопка повторной игры (при нажатии на кнопку, игроку должен снова показываться первый экран).

2022-06-24 08:04 UTC, mrerberg requested changes

2022-06-24 08:04 UTC, mrerberg commented on src/function/gameFunctions.ts
> +    if (gameData.timers != null) {
!==

Без приведения типов

2022-06-24 08:04 UTC, mrerberg commented on src/function/gameFunctions.ts
> +    interface IDataEntry {
`IDataEntry` ты написала I в начале, говоря о том, что это интерфейс. Это венгерская нотация. Она не нужна, если есть статическая типизация и вывод типов в редакторе кода

2022-06-24 08:04 UTC, mrerberg commented on src/function/gameFunctions.ts
> +    if (gameData.level != null) {
!==

2022-06-24 08:04 UTC, mrerberg commented on src/function/gameFunctions.ts
> +export function flipCard(this: HTMLElement) {
Почему в аргументы приходит this? Это не подходящее название для аргумента

2022-06-24 08:04 UTC, mrerberg commented on src/function/gameFunctions.ts
> +export function flipCard(this: HTMLElement) {
Так как в js this ссылается на scope

2022-06-24 08:04 UTC, mrerberg commented on src/game-data.ts
> +    blocks: any
А что тут примерно должно лежать? Чтобы я помог тебе описать типы

2022-06-24 18:51 UTC, TTurkevich commented on src/screen/start.ts
> +    const container = document.querySelector('#container') as Element
![comment1](https://user-images.githubusercontent.com/101629383/175647032-f55336e0-581f-4494-bf0a-3c28ef31b6a4.jpeg)

Тогда еще писать проверку надо?

2022-06-24 18:52 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +    for (let i = 0; i < levelBox.length; i++) {
ок

2022-06-24 18:52 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +    if (gameData.timers != null) {
упс

2022-06-24 18:53 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +    interface IDataEntry {
насмотрелась подозрительных блогеров

2022-06-24 18:53 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +    if (gameData.level != null) {
снова упс

2022-06-24 18:57 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +        cards.forEach((card: any) => {
![comment7](https://user-images.githubusercontent.com/101629383/175648029-f5beb905-5b5d-4ed7-8586-10227db772a2.jpg)

как-то вот так тогда выходит

2022-06-24 19:03 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +export function flipCard(this: HTMLElement) {
Оно туда не входило до typescript, а он ругается,  а так не ругается )) Переписывать все без this?

2022-06-24 19:22 UTC, TTurkevich commented on src/game-data.ts
> +    blocks: any
Там лежит объект с  ключами-названиями блоков-элементов и функции, которыми они создаются
![comment8](https://user-images.githubusercontent.com/101629383/175649558-014892f2-1132-440a-884d-b573dff48138.jpg)


![comment9](https://user-images.githubusercontent.com/101629383/175650004-eaa4252a-7f02-4e1b-896c-37bfed322b61.jpg)


Потом из блоков формируется экран 
![comment10](https://user-images.githubusercontent.com/101629383/175650204-67407228-7915-423b-a9df-6ac21cd41661.jpg)

и с помощью функций из файла render.ts все это читается
![comment12](https://user-images.githubusercontent.com/101629383/175651470-09bd8326-5648-4a50-8321-913a6baa8bb8.jpg)

![comment11](https://user-images.githubusercontent.com/101629383/175650557-272be923-76d2-496f-8b10-b0048a366f34.jpg)

2022-06-25 18:30 UTC, TTurkevich commented on src/game-data.ts
> +    blocks: any
Попыталась дописать в новом коммите

2022-06-25 18:40 UTC, TTurkevich commented on src/function/gameFunctions.ts
> +export function flipCard(this: HTMLElement) {
Не нашла решения, что делать с this. Хотела переписать без него, но в результате вылезла куча ts-ошибок с перегрузками. Оставила пока, чтобы подумать, может Вы что-то подскажите. Может this вообще нельзя в ts?

2022-06-26 13:08 UTC, mrerberg commented on src/screen/start.ts
> +    const container = document.querySelector('#container') as Element
Ошибка говорит о том, что данный элемент может быть не найдет потенциально. Да, просто следует делать првоерки

2022-06-26 13:09 UTC, mrerberg commented on src/function/gameFunctions.ts
> +    if (gameData.level != null) {
Можешь == вынести в настройки линтера, не надо за этим самому следить)

2022-06-26 13:09 UTC, mrerberg commented on src/function/gameFunctions.ts
> +        cards.forEach((card: any) => {
Значит тип не Element. HtmlElement?

2022-06-26 13:10 UTC, mrerberg commented on src/function/gameFunctions.ts
> +export function flipCard(this: HTMLElement) {
this - это из js. В твоем случае нужно просто переименовать аргумент

2022-06-26 13:16 UTC, mrerberg requested changes

2022-06-26 13:16 UTC, mrerberg commented on src/blocks.ts
> +function renderStartShell(container?: HTMLElement) {
По поводу необязательного аргумента. В данном случае, проще ожидать, что аргумент придет. Соотвественно, в месте, где вызывается функция, надо делать проверку на существование container. Мне кажется так.

2022-06-26 13:16 UTC, mrerberg commented on src/blocks.ts
> +    const start = document.getElementById('start-button') as HTMLButtonElement
as? Помним, что это крайний случай

2022-06-26 13:16 UTC, mrerberg commented on src/function/gameFunctions.ts
> +    interface DataEntry {
Интерфейсы и типы не следует объявлять внутри функции, вынеси объявление в файл

2022-06-26 13:16 UTC, mrerberg commented on src/function/gameFunctions.ts
> +    interface DataEntry {
Из функции, короче)

2022-06-26 13:16 UTC, mrerberg commented on src/game-data.ts
> +interface Result {
А result чего?

2022-06-26 13:16 UTC, mrerberg commented on src/game-data.ts
> +interface Result {
Игры? Тогда я бы так и написал GameResult

2022-06-26 13:16 UTC, mrerberg commented on src/game-data.ts
> +        [key: string | number]: string | number | null
Ключами только строки будут, нет?

2022-06-26 13:16 UTC, mrerberg commented on src/game-data.ts
> +type Func = (container: HTMLElement, data?: Data) => void
Слишком абстрактное имя для типа

2022-06-26 13:16 UTC, mrerberg commented on src/game-data.ts
> +interface Blocks {
Можно еще 

```
type Blocks = Record<string, Func>
```

2022-06-28 07:11 UTC, mrerberg approved these changes

2022-06-28 08:33 UTC, merged